### ISSUE TITLE
Authentication: Security expired midway through an upload of 400 files, blocked all requests

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#101]
403: The security validation for this page is invalid and might be corrupted. Please use your web browser's Back button to try your operation again.

This happened in the middle of a huge upload of 400 files, just came out of nowhere halfway through and blocked all following requests. 

Identify the problem, is there anything that can be done about this?

Workaround is: 
Don't upload more than 50 files in one go, if this happens, you can try again.

**Comment by ng-marcus** [comment]
@LBoyle it sounds like the digest header expired.   Is your code using REST or PnP?  
Is using PnP it should refresh the digest itself, but it using REST, we can either convert to PnP or pass the Spfx context down into the App so we can request a fresh digest.

**Comment by ng-marcus** [comment]
Please confirm resolved in https://github.com/nittygritty-uk/Atvero/pull/140 .

**Comment by LBoyle** [comment]
Will do, I suspect it'll be tricky to induce

**Comment by LBoyle** [comment]
Got it, working properly
