### ISSUE TITLE
Cannot edit a contact

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#105]
Try to edit a contact, the company  and location dropdowns greyed out

**Comment by LBoyle** [comment]
So I found this prints the error "Can't find hubSite contact guid...", means the contact record doesn't have the parentGuid populated, which is required. 
Without it, we can't perform updates to global contacts, so can't update contacts at all.

**Comment by LBoyle** [comment]
I managed to create a contact with no parentGuid. 
Most contacts have the parentGuid populated, but not the one I created. 

Identify why parentGuid isn't always updated.

**Comment by jim80** [comment]
That was not my original error Louis - it was that the dropdowns were grayed out and unpopulated.
However, now I've fixed that, I find like you that there is a problem with "Hubsite guid" ....

**Comment by jim80** [comment]
Has this EVER worked? Sorry!
My reading of the code is that it never has, though I may be incorrect.
Certainly, if I create a contact at the live Atvero hubsite, then that contact can be updated.
I suspect that the local version does not ever set Contact.parent, and that it should...

**Comment by jim80** [comment]
Done, assuming PR approved
