### ISSUE TITLE
Clicking an App menu link requires a double click

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#11]
Seems to be behaving like when the page was Home not Article.  It makes a JSON call first.  Need to research to fix.

**Comment by ng-marcus** [comment]
👍 Raising priority

**Comment by ng-marcus** [comment]
Raised as an issue on the Spfx page:

https://github.com/SharePoint/sp-dev-docs/issues/3168

**Comment by allanchaplin** [comment]
Now requires a triple click!  Added Atvero Launcher to mitigate.

**Comment by ng-marcus** [comment]
Resolved with SPFX 1.8 and server side update from Microsoft.
