### ISSUE TITLE
Far too many requests for company and address in Contacts Page.

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#115]
Noticed this on the way to solving other issues - Of course it still works fine, but does need looking at at some point, hence noting the issue here....

**Comment by jim80** [comment]
Yup, tracing all calls to CompanyRest.getCompanies shows too many still getting executed, apart from in CreateContact, where I've fixed it.

**Comment by jim80** [comment]
So, for instance, CreateCompany has the same problems that I fixed in CreateContact in respect of calling CompanyRest.getCompanies
Also, a similar situation seems to exist with Rest calls to get contacts.

I'm thinking this is probably best addressed by changing the way the whole group of components works, rather than fixing the way it is currently "working" - I had a feeling it wasn't right when I was working on CreateContact to be honest.

Probably should have spotted this before, sorry :(

**Comment by ng-marcus** [comment]
Jim, 

I agree, we should look to fix it properly for all components.

**Comment by jim80** [comment]
Sorry to bother with the email ping in the evening Marcus (and others)!
The architecture is all wrong at the moment - each component gets it own copy of Companies rather than having a single source of truth of companies handed down via props. If companies needs to be refreshed from server due to an addition, it's going to leave at least some components "stale" unless there's some kind of system to tell them to refresh. far better for them to callback message the Root container to refresh the "single truth" and pass that down via props.

I think I'll scribble down a diagram on paper before starting on it and work out the logic there first.

Mostly it should only affect Contacts page, but I'll need to consider that a couple of the components are used elsewhere (creating "Issues" for instance)

I missed the bigger picture when I started on this, my mistake I'm afraid.

**Comment by ng-marcus** [comment]
Resolved with Jim's contact code.
