### ISSUE TITLE
Can we incorporate BS1192 suitability codes please?

### ISSUE THREAD

**Issue by liamsouthwood** [nittygritty-uk/Atvero-Issues#117]
![image](https://user-images.githubusercontent.com/23510791/50696680-046d5d80-1038-11e9-90fd-7269acf0427e.png)

Page 25 of BS1192 (attached).
[BS_1192_2007_A2_2016.pdf](https://github.com/nittygritty-uk/Atvero-Issues/files/2727547/BS_1192_2007_A2_2016.pdf)

**Comment by ng-marcus** [comment]
We will use these values and labels in place of For Comment and For Construction

**Comment by jim80** [comment]
Hey Liam, I've added ALL the codes/descriptions as below, (replacing For Comment and For Construction). I seem to remember we may only need some, if you let me know the code (D2, A1 etc) to remove I'll do so ....

`let bs1192SuitabilityCodes: list(Types.bs1192SuitabilityCode_t) = [
  {suitabilityCode: "SO", description: "Initial status or WIP"},
  {suitabilityCode: "S1", description: "Suitable for Co-ordination"},
  {suitabilityCode: "S2", description: "Suitable for Information"},
  {suitabilityCode: "S3", description: "Suitable for Review & Comment"},
  {suitabilityCode: "S4", description: "Suitable for Stage Approval"},
  {suitabilityCode: "S6", description: "Suitable for PIM Authorization "},
  {suitabilityCode: "S7", description: "Suitable for AIM Authorization "},
  {suitabilityCode: "D1", description: "Suitable for Costing"},
  {suitabilityCode: "D2", description: "Suitable for Tender"},
  {suitabilityCode: "D3", description: "Suitable for Contractor Design"},
  {suitabilityCode: "D4", description: "Suitable for Manufacture/Procurement"},
  {suitabilityCode: "A1", description: "Approved and accepted as stage complete "},
  {suitabilityCode: "B1", description: "Partially signed-off"},
  {suitabilityCode: "CR", description: "As Construction Record documentation"}`

**Comment by jim80** [comment]
Uh! Ugly, hang on ...

let bs1192SuitabilityCodes: list(Types.bs1192SuitabilityCode_t) = [
  {suitabilityCode: "SO", description: "Initial status or WIP"},
  {suitabilityCode: "S1", description: "Suitable for Co-ordination"},
  {suitabilityCode: "S2", description: "Suitable for Information"},
  {suitabilityCode: "S3", description: "Suitable for Review & Comment"},
  {suitabilityCode: "S4", description: "Suitable for Stage Approval"},
  {suitabilityCode: "S6", description: "Suitable for PIM Authorization "},
  {suitabilityCode: "S7", description: "Suitable for AIM Authorization "},
  {suitabilityCode: "D1", description: "Suitable for Costing"},
  {suitabilityCode: "D2", description: "Suitable for Tender"},
  {suitabilityCode: "D3", description: "Suitable for Contractor Design"},
  {suitabilityCode: "D4", description: "Suitable for Manufacture/Procurement"},
  {suitabilityCode: "A1", description: "Approved and accepted as stage complete "},
  {suitabilityCode: "B1", description: "Partially signed-off"},
  {suitabilityCode: "CR", description: "As Construction Record documentation"}

That's better!

**Comment by jim80** [comment]
I appreciate there is  more work to be done of course, this is just a first step...
