### ISSUE TITLE
Contacts Page - companies info not reloading when company is added via add contact

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#124]
This in Local development - need to check it's not related to my recent work on contacts, since it seems OK on live site at the moment - need to confirm.

**Comment by LBoyle** [comment]
Tested the fix for this, it works for a single file, but there are still many requests coming from other files. 
Suggest applying the same fix to other files where this request occurs.

**Comment by jim80** [comment]
Fixed this...
