### ISSUE TITLE
Small screen woes.  

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#125]
![image](https://user-images.githubusercontent.com/20163757/50850939-46b5d800-1373-11e9-9e17-ce093c0651bf.png)

On a small screen, it's hard to use the drop down for status on the Info panel

**Comment by LBoyle** [comment]
We mean to fix this by simply hiding the scoped dropzone when the screen height is below a threshold.

**Comment by LBoyle** [comment]
Fixed in PR 349
