### ISSUE TITLE
Statuses

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#126]
![image](https://user-images.githubusercontent.com/20163757/50851002-74028600-1373-11e9-84f5-72b933e2e22a.png)

These look like the data values not the user friendly values.
Can we use BS1192 ones here too?

**Comment by ng-marcus** [comment]
(spacing between the words)

**Comment by LBoyle** [comment]
Get ready for this one...

"label": BSStatus.toString(s), 
"value": BSStatus.prettyPrint(s),

Must be swapped around. 

PR on the way.

**Comment by LBoyle** [comment]
Fixed in PR 248

**Comment by jim80** [comment]
"Can we use BS1192 ones here too?"
If I can work out they are, most probably! Having had a quick scan of the spec, not much is jumping out at me.

"15 Status
15.1 Principles
The identification and management of the “status” of containers should
follow the principles given in Clause 4.
BS 1192:2007
22 • © BSI 2007
13 Number
13.1 Principles
A sequential number should be used when a container is one of a series
not distinguished by any other of the fields defined in Clauses 6 to 12.
NOTE This applies most often to files.
13.2 Standard coding for numbers
The numbering for standard coding should be exactly four integer
numeric digits, used sequentially. Leading zeros should be used.
NOTE There is no need to mandate any codes for this field.
13.3 Project specific coding
There is no further restriction for project specific coding but care
should be taken not to embody information present in other fields.
14 Description
14.1 Principles
Descriptive text should not be used to imply further distinctions of
meaning. However, descriptive text derived from the other fields and
used consistently can be used to aid recognition.
NOTE 1 This implies that this field is able to be deduced from the other
fields.
NOTE 2 Avoid long, unwieldy and poorly worded descriptions.
14.2 Standard coding for description
NOTE There are no standard codes mandated for the description field.
14.3 Project specific coding
NOTE There is no further restriction for the project specific coding of the
description field.
15 Status
15.1 Principles
The identification and management of the “status” of containers should
follow the principles given in Clause 4.
© BSI 2007 • 23
BS 1192:2007
15.2 Types of “status”
15.2.1 General
If repositories are not able to track the “status” of each container (for
example a model or drawing) then its “status” should be tracked
through using two fields together:
a) suitability (see 15.2.2); and
b) revision (see 15.2.3).
NOTE The “suitability” and “revision” of a document changes during the
design process.
15.2.2 Suitability
Every container should have a field indicating the approved “suitability”
for use of the contained information.
15.2.3 Revision
Every container should carry a “revision” field, indicating the issue
sequence of the contained information."
