### ISSUE TITLE
Numbering: Can't fill in gaps in numbering 

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#128]
Gaps in numbering can be caused by using the batch uploader to create documents. 
I ask the lambda for a number three times, if they're all taken I go and find the highest taken number and add one to it. I do this because it's one simple pnp query.

I can't think of a way to find gaps in the numbering with a direct query to SP, would have to make a few much larger requests. 

Task: Think of a way to do it.

**Comment by ng-marcus** [comment]
Resolves in PR205.

**Comment by ng-marcus** [comment]
Finally closed in PR209
