### ISSUE TITLE
Topbar: Document create - nothing happens when OK is press on successful document create

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#13]
From the topbar in sharepoint

**Comment by LBoyle** [comment]
Still present,
This is because the dialog dismiss callback being passed into the component is {_ => ()} and so does nothing. Should be an easy fix to have it close the panel or something.

**Comment by LBoyle** [comment]
This is fixed in PR #161

**Comment by LBoyle** [comment]
Waiting for deploy to test this

**Comment by LBoyle** [comment]
Yes, this works, closes the panel
