### ISSUE TITLE
Contacts page - Import contacts does not work, shows error

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#130]
This is on Live site - https://atverodev.sharepoint.com/sites/LSB24/SitePages/Contacts.aspx
(local testing shows the same issue)

open import contacts dialogue, choose a couple of contacts, click oK, wait ....

Get error dialogue, with message "Contacts: Failed to import contacts"

Also, the import contacts dialogue is left in an unusable state after the error...

:( The sadness :(

**Comment by jim80** [comment]
Copy/imports dialogue does not close when copying succeeds and you click OK - this might be by design but It's a bit inconsistent with the rest of them.

**Comment by jim80** [comment]
Right, narrowed this down to it errroring when you try to copy/import "Nick Grit", most of the others seem to work fine. Probably it has company information missing in contacts table, a few do :(

look in https://atverodev.sharepoint.com/sites/AtveroHub/Lists/Contact/AllItems.aspx

A few contacts have company and address information missing, this seems to cause the failure.

Probably need to repro and kill whatever it was that caused those to be missing...

**Comment by jim80** [comment]
Progress report - these are largely fixed, but I'm still working on hiding any faulty global contacts from users in production whilst tagging them in development.
I'll leave open for now, but it should no longer be a metter of great concern

**Comment by jim80** [comment]
Annoyingly, when you request the hub contacts from sharepoint, if the hub company and/or address lookup is blank then it gets "Clever", and should you have that company in your project than it substitutes the local project lookups instead. So you cannot test for those fields being null! GRRRRRR! This has confused me for some (wasted and frustrating ) time :( 
I don't know if there is any solution to this, I guess the circumstance was caused by a previous bug, so perhaps we should not worry too much.
Just logging it. In case it happens again having a record in this Issue may prove useful.

**Comment by jim80** [comment]
Mystery solved, thanks to that pesky kid Marcus.
The bug in copy/imports contacts had resulted in sharepoint showing blanks in those hub contact records (even after force refreshing), however, it was in some sense storing those incorrect values and it was those that were returned when we queried the tables.
Editing the list in share point, changing nothing, and then saving resulted in the desired behaviour, that of actually returning a null.

**Comment by jim80** [comment]
So, I am now able to filter out these records, thus avoiding errors. Nice

**Comment by LBoyle** [comment]
Is this still an issue? 
I can import contacts now with no problems.

**Comment by jim80** [comment]
I've fixed the bug that caused it, and repopulated the hub contacts table so it should be fine, with the exception of "Nick Grit", "whom" I left for testing (when we have the "safe" version of contacts going).
Generally speaking, I think it's fixed enough to be closed.
