### ISSUE TITLE
Crash on ChapmanTaylor space creating a new DMS document

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#135]
In the C049KAM creating a new appointment letter fails with the following error.

Error: Error making HttpClient request in queryable [500]  ::> {"odata.error":{"code":"-2130575169, Microsoft.SharePoint.SPDuplicateValuesFoundException","message":{"lang":"en-US","value":"The list item could not be added or updated because duplicate values were found in the following field(s) in the list: [ATVNumber]."}}}
    at new t (atvero-web-part_477be7c5e07f4f23311c14076ea1e3f6.js:45)
    at atvero-web-part_477be7c5e07f4f23311c14076ea1e3f6.js:45

**Comment by LBoyle** [comment]
This problem might occur if category or number in the template has been changed during the life of the project. 
We need both TemplateBlocks and NumberTemplateBlocks set correctly for the CT method. 
Also it's conceivable that going up UI versions on a site with existing data could cause problems, for now anyway.

**Comment by LBoyle** [comment]
Fixed in PR #181
