### ISSUE TITLE
Provisioning: Some valid name blocks are rejected because they're not in DynamicParts

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#144]
For example Category 00 is not on the list, so the UI thinks it's not valid. 
The same goes for file Types, LTR is not on the list for example. 

This means you can't drag and drop DMS files of any kind, because the validation checks against dynamic parts, which doesn't contain all the valid blocks.

**Comment by LBoyle** [comment]
I think category only has "00" missing,
though type has quite a few

**Comment by allanchaplin** [comment]
Added 00.

Added the CT doc types to their hubsite from SH's document.
