### ISSUE TITLE
Reditions / File Type not showing on Issue Sheet

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#145]
PDF / DWG icons not showing for P1 issue of placeholder in Issue Sheet

![capture](https://user-images.githubusercontent.com/44202559/51111856-6a56a380-17f5-11e9-86b2-90e301ff996e.PNG)
![capture3](https://user-images.githubusercontent.com/44202559/51111859-6b87d080-17f5-11e9-8002-2860a3544f36.PNG)
![capture2](https://user-images.githubusercontent.com/44202559/51111862-6cb8fd80-17f5-11e9-9420-c60a197ab471.PNG)

**Comment by jim80** [comment]
We believe we've resolved this issue, and have checked on CT - it looks fine now.
Please do let us know if this is not the case, however.
Many thanks for reporting.
