### ISSUE TITLE
System accepts uploaded file with invalid number silently.

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#146]
If I upload a file with a 5 digit number onto a site expecting a 4 digit number, it proceeds happily to create a placeholder, but truncates the last number, so there's no revision.

e.g.

BGYDEMO-ATV-01-B2-DR-A-30005.pdf

becomes

BGYDEMO-ATV-01-B2-DR-A-3000

**Comment by LBoyle** [comment]
MR and I solved this, it's no longer an issue as of PR #188

**Comment by LBoyle** [comment]
The code is now much nicer, but this problem is still present.

**Comment by ng-marcus** [comment]
has the latest code fixed this?

**Comment by LBoyle** [comment]
This is fixed
