### ISSUE TITLE
filtering of files without proper metadata

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#148]
If I have a received file without metadata, it appears in all results.
For example in the screenshot, the CNM file is received, has no metadata set, yet appears when I filter on Agenda types

![image](https://user-images.githubusercontent.com/20163757/51125943-c7fce700-1819-11e9-8f6d-59ba562cda44.png)

**Comment by LBoyle** [comment]
This is probably because of a default in case the metadata item isn't present, just pass true without running any conditionals. This should be easy to fix by switching a boolean return in one of the filter functions.

**Comment by LBoyle** [comment]
Fixed in PR 256
