### ISSUE TITLE
When changing the document type, the quick parts don't update

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#15]
When I choose a document type, then change group and document type, the quick parts don't update

![image](https://user-images.githubusercontent.com/20163757/48705501-34c87c00-ebf1-11e8-970a-f628021c639b.png)

**Comment by LBoyle** [comment]
This was using ~value= for a Dropdown, but it wants ~selectedKey= instead.
Removed ~value from the Props type.
