### ISSUE TITLE
Metadata editing on uploaded files

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#157]
After uploading a PDF and DWG, I went to edit the meta data

I can't set a title - which I should be able to, but I can choose a new level, zone, type etc, which I shouldn't be able to do because the files has a revision

![image](https://user-images.githubusercontent.com/20163757/51168741-0c33ca00-18a2-11e9-8c31-b3b65a3572e2.png)

**Comment by LBoyle** [comment]
I fixed this, then when I tested a change of Document Title, it broke the placeholder horribly. 
The form assumes you have a New placeholder, so deletes the previous folders and creates new ones. Meaning it deletes the files previously uploaded. 

You can fix by clicking on it, then using the scoped uploader to upload a pdf.

**Comment by LBoyle** [comment]
Fixed in PR #186
