### ISSUE TITLE
some emails are being filed with missing metadata

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#159]
In this instance, according to Louis, it was one email from github that was missing a "to" entry.
It lead to a nasty error from somewhere in the oData conversion I think, preventing the whole page from loading.

error below : FWIW

EmailList.bs.js:331 Uncaught TypeError: Cannot read property 'split' of null
    at EmailList.bs.js:331
    at copyAuxWithMap (belt_List.js:313)
    at mapU (belt_List.js:527)
    at Module.map (belt_List.js:535)
    at EmailList.bs.js:328
    at Module._1 (curry.js:64)
    at Object.render (ReasonReact.js:313)
    at finishClassComponent (react-dom.development.js:8389)
    at updateClassComponent (react-dom.development.js:8357)
    at beginWork (react-dom.development.js:8982)
(anonymous) @ EmailList.bs.js:331
copyAuxWithMap @ belt_List.js:313
mapU @ belt_List.js:527
map @ belt_List.js:535
(anonymous) @ EmailList.bs.js:328
_1 @ curry.js:64
render @ ReasonReact.js:313
finishClassComponent @ react-dom.development.js:8389
updateClassComponent @ react-dom.development.js:8357
beginWork @ react-dom.development.js:8982
performUnitOfWork @ react-dom.development.js:11814
workLoop @ react-dom.development.js:11843
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
replayUnitOfWork @ react-dom.development.js:11318
renderRoot @ react-dom.development.js:11885
performWorkOnRoot @ react-dom.development.js:12449
performWork @ react-dom.development.js:12370
performSyncWork @ react-dom.development.js:12347
requestWork @ react-dom.development.js:12247
scheduleWorkImpl @ react-dom.development.js:12122
scheduleWork @ react-dom.development.js:12082
enqueueSetState @ react-dom.development.js:6644
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:238
sendMethod @ ReasonReact.js:264
_1 @ curry.js:64
(anonymous) @ EmailList.bs.js:186
_1 @ curry.js:64
(anonymous) @ EmailList.bs.js:135
Promise.then (async)
loadEmails @ EmailList.bs.js:134
(anonymous) @ EmailList.bs.js:183
_1 @ curry.js:64
componentDidMount @ ReasonReact.js:86
chainedFunction @ ReasonReactOptimizedCreateClass.js:631
commitLifeCycles @ react-dom.development.js:9784
commitAllLifeCycles @ react-dom.development.js:11455
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:11594
completeRoot @ react-dom.development.js:12502
performWorkOnRoot @ react-dom.development.js:12452
performWork @ react-dom.development.js:12370
performSyncWork @ react-dom.development.js:12347
requestWork @ react-dom.development.js:12247
scheduleWorkImpl @ react-dom.development.js:12122
scheduleWork @ react-dom.development.js:12082
enqueueSetState @ react-dom.development.js:6644
./node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:238
sendMethod @ ReasonReact.js:264
_1 @ curry.js:64
(anonymous) @ App.bs.js:231
Promise.then (async)
(anonymous) @ App.bs.js:229
_1 @ curry.js:64
componentDidMount @ ReasonReact.js:86
chainedFunction @ ReasonReactOptimizedCreateClass.js:631
commitLifeCycles @ react-dom.development.js:9784
commitAllLifeCycles @ react-dom.development.js:11455
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
commitRoot @ react-dom.development.js:11594
completeRoot @ react-dom.development.js:12502
performWorkOnRoot @ react-dom.development.js:12452
performWork @ react-dom.development.js:12370
performSyncWork @ react-dom.development.js:12347
requestWork @ react-dom.development.js:12247
scheduleWorkImpl @ react-dom.development.js:12122
scheduleWork @ react-dom.development.js:12082
scheduleRootUpdate @ react-dom.development.js:12710
updateContainerAtExpirationTime @ react-dom.development.js:12738
updateContainer @ react-dom.development.js:12765
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:16069
(anonymous) @ react-dom.development.js:16488
unbatchedUpdates @ react-dom.development.js:12557
legacyRenderSubtreeIntoContainer @ react-dom.development.js:16484
render @ react-dom.development.js:16543
renderToElementWithId @ ReactDOMRe.js:28
./src/reason/src/index.bs.js @ index.bs.js:16
__webpack_require__ @ bootstrap:724
fn @ bootstrap:101
0 @ main.68aaa1e30b8d5010e445.js?68aaa1e30b8d5010e445:210852
__webpack_require__ @ bootstrap:724
(anonymous) @ bootstrap:791
(anonymous) @ bootstrap:791
react-dom.development.js:9643 The above error occurred in the <EmailList> component:
    in EmailList (created by App)
    in div (created by Fabric)
    in Fabric (created by CustomizedFabric)
    in CustomizedFabric (created by App)
    in App
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

**Comment by ng-marcus** [comment]
This is another example of where our code needs to be less fragile and survive a single bad data entry.

**Comment by jim80** [comment]
This particular error is now fixed, work is needed on preventing exceptions from null results, however
