### ISSUE TITLE
DMS file Info panel has overlap problems with small viewport height

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#16]
![screenshot from 2018-11-19 15-19-17](https://user-images.githubusercontent.com/14819677/48716136-977c4080-ec0e-11e8-8d08-a6d1c2e3e8d4.png)
![screenshot from 2018-11-19 15-19-26](https://user-images.githubusercontent.com/14819677/48716132-95b27d00-ec0e-11e8-8c55-4aa97b8aef17.png)

**Comment by allanchaplin** [comment]
Fixed for demo.
