### ISSUE TITLE
Multi item select on contacts/companies/address lists seems pointless

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#160]
In fact I find it a bit irritating!

If just one item is selected then you get the sidepanel to edit it, selected more items closes that, but I don't see that it gets you anything else - there's no action you can take that requires multiple selections?

Am I missing something?

**Comment by jim80** [comment]
I changed this on ContactsList, which was easy enough to do in itself.
However, it did expose some previously hidden failings of the contact editing sidebar components.
That's reasonably likely to also happen with Companies and Addresses lists, so I'm holding off just for the moment.

**Comment by jim80** [comment]
Yes, had exactly the same issues with companies and addresses. Now fixed

**Comment by LBoyle** [comment]
This has been implemented
