### ISSUE TITLE
Document register looks funny when empty #337

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#17]
![48633410-28f37480-e9bb-11e8-8614-a1f4b0a65f36](https://user-images.githubusercontent.com/53964/48718000-6e5daf00-ec12-11e8-8ea9-b55a1f1bbc24.png)

**Comment by allanchaplin** [comment]
Still looks funny.

**Comment by LBoyle** [comment]
Get rid of the empty boxes, draw a line up the right hand side.

**Comment by jim80** [comment]
Sorted, PR in ... Not any trouble once I found the right place in render!
