### ISSUE TITLE
Provisioning change - new columns

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#173]
Add ATVIndex column (Yes/No) to  the

NumberTemplateBlocks
TemplateBlocks 

lists

**Comment by ng-marcus** [comment]
Sorry that should be ATVPrefix

**Comment by ng-marcus** [comment]
For BS-1192 set to true for all apart from [Number] in TemplateBlocks and false for all in NumberTemplateBlocks

**Comment by allanchaplin** [comment]
What should prefix be set to for CT numbering?

**Comment by ng-marcus** [comment]
true only for [category] in NumberTemplateBlock
