### ISSUE TITLE
After searching, filters on documents only show values for search results, even after search is cleared

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#180]

**Comment by LBoyle** [comment]
Is this on DLMS? I can't replicate it. Could you detail STR? 

I search for something, the whole page refreshes when loading the search results, 
The filters change to show only fields that have been loaded,
Click either the clear filters button, or the X in the search box, it takes a second to reload all the documents, when it's done, the filters refresh at the same time and accurately represent the data.

**Comment by LBoyle** [comment]
As a bug, perhaps, 
When you clear the search box, nothing happens and you can't submit with Enter, this is a regression from when I implemented it. 
Previously it would do the same thing when you press Enter, except send None and load with no search term.

**Comment by LBoyle** [comment]
Ok, so I was only able to reproduce this on atvero/ATVDEMO, 
I tried it on atvero/181206 and the filters came back as expected. 

So, while I still haven't identified the problem, It's narrowed down to the ATVDEMO project site.

**Comment by LBoyle** [comment]
This is now occurring across all sites, including on the local development server, so it is a regression that we've introduced somehow. 
I've been so far unable to identify any reason for this to happen, but now that it's also happening in dev, I should be able to track it down.

**Comment by LBoyle** [comment]
This was solved by the overhaul to the filtering components
