### ISSUE TITLE
Show full titles in filters

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#181]
Document filters would look nicer if the types and categories had the full name rather than the short code, 

e.g

Type
SU
DR 
AG

Should by

Type
SU Survey
DR Drawing
AG Agenda

**Comment by LBoyle** [comment]
Currently this isn't possible, we get the values from the Placeholder list, not DynamicParts. 

We'd have to get that info from DynamicParts in order to get the full name of the item, then filter them against the dumb values we're getting from the Placeholder list.

**Comment by jim80** [comment]
Done Diddley Done Done PR To Come.

**Comment by jim80** [comment]
PR in and merged
