### ISSUE TITLE
Provisioning: For discussion, add XX to dynamic parts for all sites?

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#188]

**Comment by LBoyle** [comment]
This is a larger issue now, as well as Zone and Level, do we want to have the DMS document types on all sites? As in, on the HubSite DynamicParts?

**Comment by LBoyle** [comment]
I'll make another issue for further changes

**Comment by LBoyle** [comment]
Update: 
LSB28 has all the correct DynamicParts, including Uniclass. 

It also has LTR for [type], for DMS Documents, still need to find out what the DMS Document types are and include them on the list.
