### ISSUE TITLE
Batch uploader makes the wrong decision after changing filename template

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#19]
Say you have an internal file that follows the default template, then you modify that template.
If you then drag and drop it, the batch uploader makes the wrong decision, thinking it's a received file, even though the companyCode and projectCode are correct, it no longer matches the filename template as it is in SP.

**Comment by LBoyle** [comment]
Check the filenames before you check the template

**Comment by LBoyle** [comment]
This is fixed in an upcoming PR,
So old files with an old template, when the template has been changed, are now recognised and treated normally.
