### ISSUE TITLE
Search: returned a non-match when I searched for docLevel

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#193]
I have two placeholders,
one DLM "LSB05-ATV-00-B1-CP-A-55001",
one DMS "LSB05-ATV-00-XX-LTR-A-00017".

When I search for "55", it appears to work.
One request for Title=LSB05-ATV-00-B1-CP-A-55001 returns the correct item,
One request for substring('55*', ATVDocumentTitle) returns an empty list,
One request for substring('55*', ATVDocumentNumber) returns an empty list

When I search for "B1", docLevel for the DLM placeholder,
Two requests for Title= both filenames, each returning a match, one is wrong,
Two requests for substring('B1*', ATVDocumentTitle) returning empty lists,
Two requests for substring('B1*', ATVDocumentNumber) returning empty lists

"B1" does not appear in the document content.

In the info panel, the matching item has it's rendition highlighted, the non-match has no renditions highlighted.

**Comment by LBoyle** [comment]
It's pretty likely that when filtering, if we encounter a placeholder with the metadata missing for the filter field, we just return true and keep it. 

There were other problems with search returning non-matches though so it might be something else?

**Comment by LBoyle** [comment]
While running through the test script, I searched for "Louis" and got all the newly created files as results, 
when I previewed the search result by hovering over the rendition icon in the info panel, "Louis" was nowhere to be seen. 

We're getting pother false positives and weird results.

**Comment by LBoyle** [comment]
We're likely going to get rid of the existing feature, replace it with the new one
