### ISSUE TITLE
Cannot edit revision numbers on bulk uploads

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#199]
When I edit a revision number, it switches back to valid, but approval has switched to choose

**Comment by ng-marcus** [comment]
I fixed autoChoose constants to "approve" but we should remove this code

**Comment by ng-marcus** [comment]
(all code referencing autoChoose as it's changing approve status on validation still

**Comment by LBoyle** [comment]
MR tells me this is fixed
