### ISSUE TITLE
Issue - Recipient missing from transmittals list when "create and issue" run,

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#200]
Select some files in the DLMS
Select issue
Give each placeholder a different reason
Set a media
Press "Create and Issue"
Go to transmittals.
Email is missing from the list - it does appear to be recorded because its in the Info panel

**Comment by jim80** [comment]
mmmm, just created 2 new issues and it seems information is missing in the Issues table - Notably reason and Multi Contacts. That would explain why the recipients are not being shown. If you add them manually in SP then they do show.

So something is wrong in creating issues. Oh promise chain Debug JOY! :)

![image](https://user-images.githubusercontent.com/16739058/52132708-aaac8300-2637-11e9-923d-81a74a6334ef.png)

**Comment by jim80** [comment]
So, looks like IssueRest.createIssue returns an issue without contacts info, which is probably the problem here...
I'm pretty sure that the reason needs to be stored, as well, which is maybe a separate issue.

**Comment by jim80** [comment]
Fixed the contacts missing issue, PR in... to be closed when approved.
Moving non storage of "Reason" to a different issue...

**Comment by jim80** [comment]
It's DOne.PR is merged into master
