### ISSUE TITLE
Contacts - Filtering in Addresses not working

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#201]

**Comment by allanchaplin** [comment]
Speak to LSB about this one, I think the filtering should not work

**Comment by jim80** [comment]
Yeah, the ATVAddress field is multiline, which makes it non filterable in sharepoint rest.
It's not the only example where we have this filtering problem...

**Comment by jim80** [comment]
In fact, the checkbox filters were not working in addition to the search working on the address field.
That's been fixed now.
The only hope I have for searching the address field is to split it into "Address Lines", with a plain text entry for each. Probably do-able

**Comment by jim80** [comment]
Closing this , since Everything that can be fixed is.
Searching the address field is not going to work unless we change it from being multiline

**Comment by jim80** [comment]
In fact. since we already have "All the addresses" as they say, we can filter/search on the multiline address field client side, and also avoid the network requests of server side filtering...
