### ISSUE TITLE
Unable to create new document! :(

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#209]
Repro : Check out master, go to DLMS in dev environment, in case it's site/provision specific I'm using : http://0.0.0.0:1234/placeholders/JH01
Click new document button, choose Document, project Admin, agenda , add name and recipient, press Submit.
 get Error message : "Error Failed to create Document",

Console logs : Failure : "int_of_string"

**Comment by allanchaplin** [comment]
The error occurs in line#427 of dlm/DLMPlaceholderRest.re in the function `findNumberOrNext`

On the CT numbering scheme the wantNumber is `[category]001` or similar.

**Comment by jim80** [comment]
Louis, there is Utils.int_of_string_opt if you need it...
You get an option from it rather than exception on invalid string.

**Comment by LBoyle** [comment]
Figured it out
We must have default values set in DynamicParts.
