### ISSUE TITLE
slow network - disable dropdowns until values loaded

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#21]
On very slow networks, disable dropdowns until values are loaded.

E.g. on the new DMS document form, document groups/types

**Comment by LBoyle** [comment]
I began this work dealing with another issue, #9
I've dealt with the new DMS Document form in particular, but there are a number more places where this occurs.
I'll track them down and fix them as part of this issue.

**Comment by LBoyle** [comment]
Please make new issues if and when you find cases of this.
