### ISSUE TITLE
DLMS - Document template typeAhead Does not clear once selected and you then choose another option in Document type 

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#215]
Not the worst of bugs to be fair, but it's a little untidy.

![image](https://user-images.githubusercontent.com/16739058/52129798-64075a80-2630-11e9-82ad-2c80c61d926a.png)

**Comment by LBoyle** [comment]
It never has

**Comment by LBoyle** [comment]
Fixed in PR 285

**Comment by allanchaplin** [comment]
Approved and merged
