### ISSUE TITLE
Publish Document from DLMS seems to be broken - erratic behaviour

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#216]
http://0.0.0.0:1234/placeholders/JH01

in DLMS, select an unpublished file, click "Publish" button ,get immediate error :(  (see network error below). This failed twice in a row.

This seemed to be working yesterday, iirc.

And publishing an already published file works without a problem.

And an update, just tried this again, after it twice failed (then I published an already published one) and it went through fine. It could be this one might be hard to reproduce , but that 400 error does seem to suggest something was wrong....

Bad network request : 

Request URL: https://localhost:4323/sites/JH01/_api/web/getFolderByServerRelativeUrl('DLM_Library/JH01-ATV-00-XX-AG-A-00003')/folders/add('01')
Request Method: POST
Status Code: 400 Bad Request

**Comment by jim80** [comment]
I guess this could just have been a network glitch?

**Comment by ng-marcus** [comment]
Most often 400 errors are the proxy.   Worth seeing if it can be reproduced on a real SP site.

If it says "Bad Verb" it's the proxy

**Comment by LBoyle** [comment]
This might be a 404, something I've encountered is an earlier request failing to create the filename folder, so when it tries to create the '01' revision folder, get a 404. 
I just tested this on atverodev/ATVDEMO and it worked fine a bunch of times.

**Comment by jim80** [comment]
Ok, many thanks Louis. I think we put this down to network error and close it. If it appears again at least we have a record to refer to.
Apologies if it was not really a bug!
