### ISSUE TITLE
Publish did not generate a PDF file.

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#219]
https://atverodev.sharepoint.com/sites/NUMBSEN01/SitePages/Atvero%20Docs.aspx
NUMBSEN01-ATV-00-XX-LTR-A-00-0001
Rev 01

**Comment by LBoyle** [comment]
I just got a PDF generated after publish on a brand new site, took about 10 seconds.

**Comment by jim80** [comment]
Yes Allan, I don't get one generated after publish either, when running the test script.
