### ISSUE TITLE
Contacts - Changed the name of the contact and the table/info card did not update

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#220]
Had to refresh the who page.

**Comment by jim80** [comment]
Confirmed when running test script - will add this and other issues...

**Comment by LBoyle** [comment]
Will this ever end?

**Comment by jim80** [comment]
There are lots of "fun challenges" in there to be sure.

**Comment by jim80** [comment]
Should be fixed in latest contacts PR

**Comment by jim80** [comment]
done & merged to master
