### ISSUE TITLE
DMS: Type field on create form should be a TypeAhead

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#224]
It's currently a TextField.

**Comment by LBoyle** [comment]
I did this deliberately because the dynamic parts table is still missing all of the DMS Document types, so you can't see the type of the doc you're creating, and you can't submit the form without selecting a type. 

I'll fix this when dynamic parts has everything that is required.

**Comment by LBoyle** [comment]
Fixed in PR 284

**Comment by allanchaplin** [comment]
Approved and merged.
