### ISSUE TITLE
Create Another: Discuss correct behaviour

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#226]
This was an idea I had very early on to make it easy to create files in batches. 
The system has changed quite a lot since then, so I'd like to give it a once-over.

**Comment by LBoyle** [comment]
Create another button now works properly provided you empty the number text field.

**Comment by jim80** [comment]
I saw it was back!

**Comment by LBoyle** [comment]
I didn't do that, for the record...

**Comment by LBoyle** [comment]
I'll empty that number field as a task for this, then users should be able to use it freely

**Comment by LBoyle** [comment]
Done in PR 331

**Comment by allanchaplin** [comment]
Merged
