### ISSUE TITLE
Issue Info is blank before issue (as it reads the immutable revision list)

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#23]
![47586460-34252880-d958-11e8-8c85-52509e23d7b3](https://user-images.githubusercontent.com/53964/48718500-6fdba700-ec13-11e8-91d5-4770375ecdbd.png)

**Comment by ng-marcus** [comment]
I think this was fixed ages ago?

**Comment by LBoyle** [comment]
Yes appears to be fixed
