### ISSUE TITLE
Contacts: Some forms allow you to submit with incomplete input

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#231]
New address form can be submitted without filling it in completely. 
I suspect this happens in other places as well.

**Comment by jim80** [comment]
I cannot reproduce this with CreateAddress.re - the submit button is disabled until there is something in each required field.
That's not to say this is the case with other forms.of course.

**Comment by jim80** [comment]
Still noticed any of these. Any chance you can reproduce one Louis? You'll then have the chance to see me eating my hat ;)

**Comment by jim80** [comment]
Assigned it to you for feedback only, assign it back to me when and if answered and I'll see what I can do to fix, if it needs it.

**Comment by LBoyle** [comment]
No can't reproduce, I don't remember the circumstances

**Comment by jim80** [comment]
No problem!
To close or not to close? This is the question.

**Comment by jim80** [comment]
Aha - in fact CreateCompany was not validating City, though that is a funny one since it didn't have city before I patched it up to do so!

**Comment by jim80** [comment]
I've now fixed that one...

**Comment by LBoyle** [comment]
Righto

**Comment by jim80** [comment]
OK, checked them all, all looks now. Will close when PR merged...

**Comment by jim80** [comment]
Done and PR merged...
