### ISSUE TITLE
Shouldn’t be able to add the same two contacts (SH)

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#249]

**Comment by jim80** [comment]
Is this the same as 
https://github.com/nittygritty-uk/Atvero-Issues/issues/254
?

**Comment by jim80** [comment]
Maybe not, it may well refer to adding another contact with the exact same details as an existing one.
I don't think there is any check preventing one from doing this...

**Comment by jim80** [comment]
#254 I think may be the manifestation of the consequences of doing this...

**Comment by jim80** [comment]
This is effectivelt done, since we now prevent 2 duplicate contacts being created...
