### ISSUE TITLE
Clicking on ‘Associated Files’ button then back to ‘Renditions’ removes all upload options. (SH)

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#250]
The upload should hold and only disappear if the user deletes

**Comment by LBoyle** [comment]
This is because we have a conditional in render, and switching un-mounts one and mounts the other.

**Comment by LBoyle** [comment]
Got this working for the scoped uploader with Placeholders, not DMS because don't ever switch  uploaders. 

Yet to do batch uploader.

**Comment by LBoyle** [comment]
Fixed in PR 350
