### ISSUE TITLE
Duplicate contacts can be added to an issue

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#254]

**Comment by jim80** [comment]
Will check this out...

**Comment by jim80** [comment]
Oh, it looks oK to me. Which means I probably misunderstand something.
I'll get you to illustrate when you're in...

**Comment by jim80** [comment]
Ok, cannot reproduce. Chatted to Allan, we think it might be a duplicate contact, which he's checking on CT's account

**Comment by jim80** [comment]
There are 2 identical contacts in the hubsite at CT, it was these contacts that SH had identified as duplicate in issues.
Why that has happened I don't know at this stage.

**Comment by jim80** [comment]
See https://github.com/nittygritty-uk/Atvero-Issues/issues/249
For how it may happen...

**Comment by jim80** [comment]
We've fixed the being able to create 2 identical contacts thing, presumably this maybe means this can be closed?
