### ISSUE TITLE
Submit button appears greyed out after a DMS document is created

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#255]
![screenshot 2019-02-06 at 14 25 39](https://user-images.githubusercontent.com/53964/52348059-53cdf180-2a1b-11e9-8cce-15f1bf3b41b3.png)

**Comment by jim80** [comment]
https://github.com/nittygritty-uk/Atvero-Issues/issues/214

**Comment by jim80** [comment]
https://github.com/nittygritty-uk/Atvero-Issues/issues/226

**Comment by jim80** [comment]
make a decision Allan! What should I do? !! Sorry!

**Comment by jim80** [comment]
Assign it back to me when you've let me know, and I'll get it done, thanks!

**Comment by jim80** [comment]
I've gone ahead and hidden it anyway, close this when you've checked the PR and merged?

**Comment by jim80** [comment]
OK, closing it due to no response, you busy man ;)
