### ISSUE TITLE
Contacts - When the info panel is open the table squashes up - on other pages it slides underneath

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#258]

**Comment by jim80** [comment]
Yeah, it's bloody irritating and looks shite. I'll need to suss out the markup/.css for this.

**Comment by jim80** [comment]
Thanks to tips from Allan - needs a min-width setting for each td, so some scss work required.

**Comment by jim80** [comment]
Added some min-widths to the table headers, which largely fixes this issue.
PR is in...

**Comment by jim80** [comment]
done & merged to master
