### ISSUE TITLE
Contacts - Companies list not alphabetically sorted

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#260]

**Comment by jim80** [comment]
I'll have a look at this. Thanks.

**Comment by jim80** [comment]
In fact, NONE of the lists appear to be sorted in any way at all (Maybe creation order, I guess).
Ideally, we'd have a column header that sorted on that column, as per DLMS.
Less ideally, and far quicker, I could probably add an alphabetic sort by default without much trouble.

**Comment by jim80** [comment]
After conference with Allan, should be doable in the SP query...

**Comment by jim80** [comment]
Done ....
