### ISSUE TITLE
DMS Document type is not getting picked up from the Document Types table

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#262]
In ATVDEMO on atverodev, the Agenda has a type of AG, but it appears as LTR.

The type of the document is available in Document Types.

**Comment by LBoyle** [comment]
Did you fix this? I'm not getting it, perhaps I don't understand the problem.

**Comment by LBoyle** [comment]
Also atverodev/ATVDEMO doesn't have the up-to-date DynamicParts, or at least doesn't have uniclass. It has a default role. 
Though I don't think this is causing your problem.

**Comment by ng-marcus** [comment]
I think this is a more general issue - the default values for these values should come from the Document Types table.  Same for things like PCF, scale/size

**Comment by LBoyle** [comment]
This is fixed along with multiple filename templates per project.
