### ISSUE TITLE
Document Register: Make the document number column smaller to leave more space for the document title

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#270]

**Comment by LBoyle** [comment]
Worth noting some numbers might be longer and take up all that space as well.

**Comment by LBoyle** [comment]
It was previously 20 rem for both columns, I think 17 / 23 rem looks pretty good.

**Comment by LBoyle** [comment]
In PR 332

![screenshot from 2019-03-06 10-35-07](https://user-images.githubusercontent.com/14819677/53875045-a212e800-3ffb-11e9-9550-40360b668017.png)

**Comment by allanchaplin** [comment]
Merged
