### ISSUE TITLE
Filtering - changes

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#278]
We need to change the filtering for placeholders.

The simple change is that we derive the current filters based on the filtered data, so that once you choose a drawing, you can only see levels that match the current drawing.

Here's something I think would be nice, but hard.   The first group you choose from never loses all the values.  So you could choose DR, and all the other groups filter, but you could then add CO to the filter list.

Only way I can think of to implement that is whenever there's only one group selected, it sets itself as the "primary" group, until there are no groups with selections,.

**Comment by LBoyle** [comment]
Got this working with help from MR
