### ISSUE TITLE
Cannot set uploaded by or title on First revision from upload area in info panel (DLMSHome)

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#282]
As per title - add a file to upload area in placeholder info panel, click "customise" set fields title and uploaded by, click "Close" *, then reopen by clicking "customise" again - fields are now empty.

This does work on the second revision, and it does work on the uploaded on the main "Upload" button.

* crap interface there, needs updating also

**Comment by jim80** [comment]
PR in ...

**Comment by LBoyle** [comment]
Was this merged? Can we close the issue?

**Comment by jim80** [comment]
Yes, ta.
