### ISSUE TITLE
Upload button remains enabled if you delete ALL files in upload dropzone.

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#284]
Clicky clicky upload btn at top, browse or drag a file to dropzone, assuming it's valid the upload button will enable itself. Now delete that file by clicking it's little dustbin symbol.
The upload button remains enabled...

**Comment by LBoyle** [comment]
Nothing bad can happen if you press the wrongly enabled button, incidentally.

**Comment by jim80** [comment]
Apart from a red error message!
No, not a bad bug, just noting it for a later tidy up...

**Comment by LBoyle** [comment]
Fixed in PR 294

**Comment by allanchaplin** [comment]
Merged
