### ISSUE TITLE
Customise modal for file uploads have only a close button.

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#289]
The close button also updates the revision with whatever is in there, which maybe a little unwanted in some scenarios.

I'd say it probably wants some thing like an "update" or "save" buttons, and in addition also a cancel button...

**Comment by jim80** [comment]
Ah, when I actually think about it, any change to fields within  these modals is  immediately propagated upwards, so having a cancel button won't really work at this point in time - the "save" or change is already done.
Would have to save changes in local state and then push them up on the "save" button click.
Which is a bit of a bigger job...

**Comment by LBoyle** [comment]
We could do the more traditional Save / Cancel sort of thing fairly easily. 
Which of the two do we want?
