### ISSUE TITLE
Hard Crash - create DMS document causing JS exception

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#290]
Just provisioned https://atverodev.sharepoint.com/sites/ACPA005 when creating a DMS document in Sharepoint or in the Workbench get a an error

`Uncaught TypeError: Cannot read property 'length' of null`

The problem appears to be in DMSFileRest.re line 144 as company is null

```
let isReadyForSubmit = (file: DLMPlaceholder.t): bool =>
  switch (file.nameBlocks) {
  | None => false
  | Some(nameBlocks) =>
    switch (
      Js.Dict.get(nameBlocks, Constants.template_company),
      Js.Dict.get(nameBlocks, Constants.template_dmstype),
    ) {
    | (Some(company), Some(type_)) =>
      String.length(company) > 0 && String.length(type_) > 0

    | _ => false
    }
  };
```

**Comment by LBoyle** [comment]
That company code comes from props for Spfx.re, in dev from SharepointHost

**Comment by LBoyle** [comment]
I tried to replicate the bug on another site and couldn't, then went back to ACPA005 and couldn't replicate it there again either.

**Comment by allanchaplin** [comment]
Not repeatable in 2.1.10.3 closing
