### ISSUE TITLE
Issue List: Issue progress bar isn't going away or finishing at all

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#297]
Just spins forever, no pending requests. 
It does successfully issue files I think, it all works after a refresh as though they were successful.

**Comment by LBoyle** [comment]
Had a look at this, it's on line 325 in Issues.re
I'm not going to take it because it's the callback pattern, not in that headspace right now.

**Comment by allanchaplin** [comment]
merged
