### ISSUE TITLE
DnD files with wildcard number fails horribly

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#30]
We think that dropping on a file with a wildcard for the number, like "...-21###.pdf", fails when it should generate a number.

Note:
When the decision is made, no placeholder metadata is put into the action.placeholder, I need to get the data from the filename and put it into the action.

**Comment by LBoyle** [comment]
This no longer fails, it just uses whatever string you have in the number position. 
Number isn't validated at all at the moment.

**Comment by LBoyle** [comment]
PR #143 blocks attempts with a wildcard number, get an error action telling you not to use wildcards.
