### ISSUE TITLE
DLM - Weird Infinite loop when trying to issue

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#300]
On master - open DLM select some files, hit issue.  The network tab goes crazy with requests.

**Comment by LBoyle** [comment]
We've got to load three things, when the selected placeholders change, 
issuedDocuments, issuedContacts and all revisions for selected placeholders. 

There are also a bunch of self.send's that can cause races. 

I think we've got to overhaul all the rest for this component (excluding contacts) to get it behaving again.

**Comment by LBoyle** [comment]
Going to try and fix this by not always rendering it.
Instead, switch and render if the conditions are met.

**Comment by LBoyle** [comment]
Fixed in PR 301

**Comment by allanchaplin** [comment]
merged
