### ISSUE TITLE
Created new Agenda document - name did not include AG ...

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#301]
First task in test script!

**Comment by LBoyle** [comment]
This is because DynamicParts is missing the new [dmstype] types, need all of them in DynamicParts as well as Document Types. 
If it isn't present, it defaults to LTR which is the default.

**Comment by LBoyle** [comment]
I think provisioning only copies the list if the actual list isn't present on the Project site, so to solve this problem, 
Delete your whole DynamicParts list from your Project site, and have AC run the provisioning again.

**Comment by LBoyle** [comment]
We suspect this happened because my bugfix from yesterday hasn't yet been released to atverodev.
Test again after we release.

**Comment by allanchaplin** [comment]
Fixed
