### ISSUE TITLE
add the sentry logger to the error message handler for spfx?

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#309]
Way too many false positives coming from Sharepoint.  Now that we have a single point for showing errors should we log sentry there?

**Comment by jim80** [comment]
I think that handles errors we've already caught, not those we have not? So a good idea, but perhaps not all encompassing.
Here's an idea that may or may not have merit - cam we Surround the whole of spfx in a try/catch? We're in Javascript land when we render spfx, so I'm thinking something along the lines of - 
try{
ReactDom.render(spfx.make(), someElement)
}catch (Error) {
Sentry.log(error)
}

I'm afraid I forget the syntax, hopefully the meaning is clear though!

**Comment by jim80** [comment]
Annoyingly, reasonReact does not support the react errorBoundries API - I checked a few days back.

**Comment by jim80** [comment]
No, it does not work like that :(

**Comment by jim80** [comment]
Apparently the "level" above spfx is a react generated component though? At least Allan gave me that impression. Can we put an error Boundery on that one?

**Comment by jim80** [comment]
Indeed we can - example PR on the way...

**Comment by jim80** [comment]
I guess we could "just" pass a function prop down into spfx that calls Sentry.doyourloggingthang(), with the error component at the top, there's not a lot of drilling to be done. It would be good info to capture - the Error Boundary is a last ditch that catches unhandled exceptions, not those that we've caught and dealt with.

**Comment by jim80** [comment]
Closing this, since the base work is done - there are other issues to take it further..

**Comment by jim80** [comment]
https://github.com/nittygritty-uk/Atvero-Issues/issues/399
