### ISSUE TITLE
DLM Home - filter and sort need to be based on last revision creation, not placeholder

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#310]
When filtering on the document list, if I set to one day I can only see placeholders created that day, not placeholders with revisions added that day.

Similarly, sort only puts new placeholders at the top, not new revisions.

**Comment by LBoyle** [comment]
Work on getSliderFilteredFiles function in DLMHome line 363.

We just look at ph.created, we should look at ph.lastRevision.created, and fallback to various other dates.

**Comment by LBoyle** [comment]
This will be a problem no longer on the Document Register, because we're excluding DMS files from the register, and DMS specific columns from the register filters.

**Comment by LBoyle** [comment]
This is in place
