### ISSUE TITLE
Filters are in a random order

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#315]
As I make selections in the DLM home filter, the order of the filters changes, so my selections aren't on screen.

**Comment by jim80** [comment]
Just checked this with Marcus, tried it on atvDemo with plenty of files, seems this is no longer an issue.

**Comment by jim80** [comment]
Aha! Marcus has just reproduced this one - and I even saw it myself. Again, using ATVDemo.
