### ISSUE TITLE
Action Bar

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#316]
Hello,

The action bar is missing from the top of our pages. 

![capture2](https://user-images.githubusercontent.com/44202559/53014462-765f0200-3440-11e9-8f0f-c8c5166c5d48.PNG)
![capture](https://user-images.githubusercontent.com/44202559/53014464-765f0200-3440-11e9-9340-d0771c81da92.PNG)

**Comment by LBoyle** [comment]
Symptom of Issue #311, we're on it.

**Comment by ng-marcus** [comment]
Hi Stephen

Microsoft did a major change over the weekend relating to title bars in particular.  We're investigating.

**Comment by allanchaplin** [comment]
This issue has been resolved.  The topbar will return in the next release.
