### ISSUE TITLE
Make a copy of an existing document

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#319]
To be discussed.

**Comment by LBoyle** [comment]
Duplicate of #268

**Comment by LBoyle** [comment]
I'm going to start with placeholders first, then extend it to do the additional things needed for documents.

**Comment by LBoyle** [comment]
I've made some good progress on lb-bugfix-319 branch
Populate the form with most of the metadata from an existing document. There are some bits I found tricky, but is doable.

**Comment by LBoyle** [comment]
This is in PR 341

**Comment by allanchaplin** [comment]
merged
