### ISSUE TITLE
DMS version missing from info.

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#328]
![screenshot 2019-02-28 at 15 52 33](https://user-images.githubusercontent.com/53964/53579141-ef610680-3b70-11e9-8433-5fe5bb31c4cd.png)

**Comment by LBoyle** [comment]
Fixed in PR 326
JH had put a safety check into willReceiveProps, which highlighted the anti-pattern. 
Solved by making an additional request in didMount.
