### ISSUE TITLE
DLM - Several 01 revisions on placeholders

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#34]
Happened during the demo, speak to MR for more info,

**Comment by LBoyle** [comment]
![image](https://user-images.githubusercontent.com/14819677/48849389-2bc8dd80-ed9e-11e8-87f8-893e89f07428.png)

**Comment by LBoyle** [comment]
Two 01 revisions on DLM_Revisions
try to reproduce

**Comment by ng-marcus** [comment]
Can't reproduce
