### ISSUE TITLE
Search - results run together on small pages

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#340]
![screenshot 2019-03-06 at 16 29 52](https://user-images.githubusercontent.com/53964/53897415-fb940a80-402d-11e9-9b55-da7980262571.png)

**Comment by LBoyle** [comment]
I made the results full width below a certain size with a media query. 
Also there was css for height on the h3 element, and it wasn't wrapping, so rather than risk messing all the layout up, I put ```height: auto !important;``` in there instead.

**Comment by LBoyle** [comment]
Fix in PR 339
(wrong branch)
