### ISSUE TITLE
Search - pop the search highlighting a bit more

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#341]
My drab grey looks drab and... grey.  Can you take a look at how other search products do this and then use that as inspiration for a nicer highlight.

![screenshot 2019-03-06 at 16 30 03](https://user-images.githubusercontent.com/53964/53897456-12d2f800-402e-11e9-964f-a503edbab377.png)

**Comment by LBoyle** [comment]
Other search engines tend to have only slightly increased font-weight, 
What I've done is just remove the background colour, and I think it looks better, contrasts more sharply against the white background than the grey.

**Comment by LBoyle** [comment]
Fix in PR 339
(wrong branch)
