### ISSUE TITLE
Search - the search container needs a line across the top.

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#342]
Ladies and gentlemen its floating in space... who knows where sharepoint ends and Atvero begins... putting a line across the top will help.

![screenshot 2019-03-06 at 16 30 28](https://user-images.githubusercontent.com/53964/53897555-49a90e00-402e-11e9-8d8b-a260fcd58ad6.png)

**Comment by LBoyle** [comment]
Fixed in PR 340
