### ISSUE TITLE
Email search results a little inconsistent

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#354]
For instance, searching for "You" on JH04. Seems to correctly find text with "you" in it for first 2 results, however the subject and "From" for both is incorrect...

the result "Message Center Major Change Update Notification" also seems to appear with everything I search for....

![image](https://user-images.githubusercontent.com/16739058/54117857-a79c7380-43e9-11e9-8d95-63ba199a0be9.png)

**Comment by jim80** [comment]
In discussion with Louis, this *may* be down to us now using {XYZXXXXXXXXXXXXXX}/message.eml in the email library rather than XYZXXXXXXXXXXXXXX/XYZXXXXXXXXXXXXXX.eml

**Comment by jim80** [comment]
Here you go L!

**Comment by LBoyle** [comment]
Figured out this was happening because the .eml file was being names "message.eml", previously we were using the giant uuid fir the name.
