### ISSUE TITLE
In email list view, show indication as to whether email has attachments

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#355]
Suggested paperclip icon...

**Comment by jim80** [comment]
Liam requested this in internal demo...

**Comment by jim80** [comment]
One Allan has parsed attachments in the email filer this should be doable...

**Comment by allanchaplin** [comment]
Attachments are parsed and added to the list item as AttachmentExtensions so a paperclip, count or icons can be shown.

**Comment by jim80** [comment]
Closing - it now shows icons for each attachment. PR in ... should pass!

**Comment by jim80** [comment]
Done
