### ISSUE TITLE
Adding Contacts to project

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#36]
I created a new contact / org to Kampus project. All worked as should. I added a second contact / org the drop down for company will not allow preview

**Comment by allanchaplin** [comment]
Works fine first time, subsequently opening the new contact dialog, Company and Location are disabled.

**Comment by LBoyle** [comment]
After submitting the form, it remains disabled, you have to refresh to use the form again. 
I suggest a reducer that clears the form when the "OK" button is pressed.

**Comment by jim80** [comment]
Oh, there is a whole load of issues in this area, need to log them

**Comment by jim80** [comment]
This seems reasonably fixed with a couple of small updates, still have to PR it.

**Comment by jim80** [comment]
Done subject to PR approval
