### ISSUE TITLE
Issue register not showing issued DMS documents

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#360]
Show DMS documents in the issued register

**Comment by LBoyle** [comment]
Got this done by filtering the placeholders against the issuedDocuments. 
We already had everything loaded, it meets the requirements, we can look at optimising it later.

**Comment by LBoyle** [comment]
This wasn't merged, I thought it was

**Comment by LBoyle** [comment]
PR 358
