### ISSUE TITLE
Provisioning: Newly created site has three ATVLastRevision fields on Placeholder 

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#364]
As shown in the image, not sure what actually has happened. 
I think only the one with the unaltered name is made use of, don't think it impacts functionality.

![Screenshot from 2019-03-13 11-11-06](https://user-images.githubusercontent.com/14819677/54274962-53c49280-4581-11e9-9e14-2e3b0a852f24.png)

**Comment by allanchaplin** [comment]
The other two are mappings of the ATVLastRevision fields into the Placeholder list.  The graph API requires this to show them as expanded fields.  Still a bug, as there are two for ATVRevision - there should only be one.
