### ISSUE TITLE
Provisioning: New list for data about immutable issues

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#366]
PR 354 needs some new provisioning, it's an addition so provisioning over an existing site will work no problem. 

New list: IssueMetadata 
Title: guid,
ATVIssueGuid: guid,
ATVReason: single line string,
ATVIsVoid: yes/no,

We've duplicated the guids before, feedback on that if you like.

**Comment by allanchaplin** [comment]
Can you give me access to an already provisioned site for reference.

Thanks,
