### ISSUE TITLE
Clearing multiple selections

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#374]
It's a pain when I select an item and discover I have another item selected somewhere else in the list:

![image](https://user-images.githubusercontent.com/20163757/54418736-ae82f900-46fd-11e9-88ce-9a129da756c9.png)

Simple fix - add a clear selection to the X selected panel so I can reselect.
Better fix - let me select/unselect in the pane too, until only 1 is selected, then it switches to a view

**Comment by allanchaplin** [comment]
Would be nice to add an issue button the this pane too?

**Comment by jim80** [comment]
That issue button might not be too difficult to add...

**Comment by jim80** [comment]
Done, with Issue and Status button in addition.
