### ISSUE TITLE
Bulk upload unusable for received files

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#378]
Can't select the type as the dropzone is too small.

**Comment by allanchaplin** [comment]
![Screenshot 2019-03-15 at 12 12 27](https://user-images.githubusercontent.com/53964/54430503-b5206900-471b-11e9-9b36-420970ec8607.png)

**Comment by LBoyle** [comment]
In this case, the reason you can't select type is because the file matches the template, and has the type in it. 

You can't have one type in the metadata and another in the name, so I block you from changing the type.
