### ISSUE TITLE
Uppy allows name with incorrect number field (but it doesn't upload)

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#39]
If you add a file which is an internal file that matches the naming scheme, but the number is more than 5 digits, e.g. 00010 . UPPY is happy and reports no error . The file doesn't get created though.

So two issues.

One, check the numbers match the scheme
Two, it should have reported an error somewhere so the user is aware the file didn't upload.

**Comment by LBoyle** [comment]
This is fixed in an upcoming PR
