### ISSUE TITLE
Issue Sheet Freeze

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#4]
Failed to load resource: the server responded with a status of 403 ()
ng-component-web-part_9b3a52bc1f946c69eaad02047cd276b4.js:15 
Array(2)
DLM.aspx:1 Uncaught (in promise) Array(2)

I put the same contact on the issue sheet (on purpose!) I don't know if this crashed it?

**Comment by ng-marcus** [comment]
Stephen!   You troublemaker.  Thanks I'll take a look

**Comment by ng-marcus** [comment]
@LBoyle can you see if this is fixed in the latest release please.

**Comment by LBoyle** [comment]
Should have seen to this sooner,
Were getting results from both the project site, and the hubsite, because it's two separate lists, the guids are different. Check the "parent" property for the guid as well as the plain guid, when filtering the response.
