### ISSUE TITLE
Custom Filters - Show the selected filter in the custom filter drop down

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#409]

**Comment by jim80** [comment]
Damn, I thought it did that... I must have left a hole somewhere I guess.

**Comment by jim80** [comment]
Maybe when you return to DLMHome and pick up it's previous state it won't show.

**Comment by jim80** [comment]
Ok - misunderstood, put it in the title for the collapsible interface...

**Comment by jim80** [comment]
Done
