### ISSUE TITLE
A199BRCR - Library not Opening

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#411]
Hello,

Not an urgent issue but the A199BRCR library is not opening. Stuck on the spinning wheel. 

![image](https://user-images.githubusercontent.com/44202559/55318353-7f44e980-546a-11e9-8d13-c048c13dac1b.png)

**Comment by allanchaplin** [comment]
Hi Stephen, I'll take a look now.

Allan

**Comment by allanchaplin** [comment]
Hi Stephen,

It should be working now, please let me know and I'll close the issue.

Thanks,

Allan

**Comment by StephenHiggon01** [comment]
Thanks Allan now working.

**Comment by allanchaplin** [comment]
Great!
