### ISSUE TITLE
Received files should show icon

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#420]
When a file is received, its icon should be set appropriately.

For example if I upload a received PDF, the icon should be a PDF.  Set it at the time of the placeholder and revision creation.  So it would change on a new revision if the file type changed.

For multiple files in a revision, a DWG trumps a PDF, Word/Excel/PPT trumps PDF

For placeholders and revisions created locally (non received) use the DWG icon as we do now.

**Comment by LBoyle** [comment]
Went in with PR 424
