### ISSUE TITLE
Custom Filters - Selected filter get forgotten if you browse to a non ATV page

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#424]
On ATVDemo if I select a custom filter and then browse to the `Documents` sidebar item, when I browse back to Atvero Docs the filter is forgotten.

I wonder if the provisioning is correct

**Comment by jim80** [comment]
I think it's that the state gets saved when the component unmounts, which is fine if you navigate away within ATV, but if you leave it completely then willUnmount doesn't get called.
I've just noticed this myself.
We maybe need to find the global "leaving this page" event and attempt to save state on that happening...

**Comment by jim80** [comment]
"onbeforeunload" was what I was thinking of. But that's maybe overcomplicating it. If the state was just saved when the filter is _selected_ then that should be good enough...
I'll get onto that.

**Comment by jim80** [comment]
So, it now saves the state at any point that a filter changes, so no requirement to catch it on leaving the page... PR in...

**Comment by jim80** [comment]
Merged.
