### ISSUE TITLE
Multiple entries with the same value break the dropdown

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#434]
We added the ability to change the document type of DMS documents, but as some of the  have the same value, we multi-select all the items with the same value, e.g. CO

![image](https://user-images.githubusercontent.com/20163757/55564646-428a2400-56f0-11e9-9331-1e5f91181ce2.png)

**Comment by jim80** [comment]
I knew that was a bad idea! :) 

It may be a really simple fix, I'll have a look...

**Comment by jim80** [comment]
It's not a simple fix, so I'm leaving it here just for now.

The answer lies within the react-select code, I'd hoped that just seeting it's "isMulti" prop to false would cure this, but it doesn't, and it's more complicated.
There is some hope, however...

see the docs here : https://react-select.com/props
and look for this : 

isOptionSelected function
Override the built-in logic to detect whether an option is selected

function (
Object,
Array<Object>
) => boolean

**Comment by jim80** [comment]
Actually really not so hard when you actually try it out, rather than getting frightened by the lack of specific documentation on the function, as I did.
 PR'd

**Comment by jim80** [comment]
merged
