### ISSUE TITLE
DMS revisioning

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#442]
When creating a new word document, it shows as version 1.03 on first edit (before publish).

This should be version 0.03

Can we also check the number goes up in this display - Liam did some edits but we didn't see the revision number go up, even when pressing refresh.   A key part of Liam's demo so can we check please.

**Comment by jim80** [comment]
The version number seems to update if you close and reopen the info panel, I'll see if that can be made more timely...

**Comment by jim80** [comment]
So. The word doc is opened by a special URL, there's no way to tell if the document has been saved, no event or callback to tell us that. So the only way would be to ping sharepoint on a setInterval, really not sure we want to do that.

The version number - tried a change to the default version number and it did not give expected results, so need to look at the code for that...

**Comment by ng-marcus** [comment]
OK, it was more the info number in the panel - can the refresh button make the info panel update too?  Just useful for demos.

**Comment by jim80** [comment]
It seems to be utterly inconsistent - sometimes the revision number will be updated when editing and saving word file then pressing refresh button, sometimes not and you have to refresh the whole page.
