### ISSUE TITLE
Custom Filters - Costmetic issues

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#444]
![Screenshot 2019-04-08 at 10 42 19](https://user-images.githubusercontent.com/53964/55714778-2be31600-59eb-11e9-9195-59428807531c.png)

View name and saved name LHS's don't line up.

![Screenshot 2019-04-08 at 10 44 23](https://user-images.githubusercontent.com/53964/55714834-4f0dc580-59eb-11e9-8459-2a243e23d555.png)

Use a delete icon and move it inline with the typeahead.

**Comment by jim80** [comment]
Yeah. Needs attention. And in fact on live sites the save button is above the textfield so It needs sorting in any case...

**Comment by jim80** [comment]
Pr'd
