### ISSUE TITLE
Document type should indicate whether PCF is checked

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#45]
If it is checked it should be disabled - so that those docs _always_ go to the PCF

**Comment by ng-marcus** [comment]
Now that we use the same document type for all documents, need to find a new way to indicate the default value.

**Comment by ng-marcus** [comment]
Don't use content types any more, need to add to the block templates table so set the default

**Comment by LBoyle** [comment]
What the situation regarding this? We need to set this using template blocks? 
I'm going to have a look.
