### ISSUE TITLE
Email List: Email parser from npm has some problems

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#463]
Bails if the values have the wrong formatting. 

Correct: 
```"Louis Boyle" <louis@boyle.com>, "" <someone@else.com>```

Pretty much anything else fails, 
including any name with more than two words, such as "Office 365 Message Centre", it just returns null

Find another package, or make a regex for it or something

**Comment by jim80** [comment]
DId you look at this one ?

https://github.com/emailjs/emailjs-addressparser/blob/master/src/addressparser.js

**Comment by LBoyle** [comment]
Nope, looks good though. It can return a bunch of different things, so will have to be careful within Reason.

**Comment by jim80** [comment]
It's the one included with the mime parser, and I'm pretty sure I used it's output, which is an array of objects iirc.

**Comment by ng-marcus** [comment]
Fixed by Louis's own parser.
