### ISSUE TITLE
DMS: Revision and document version are different.

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#47]
Its confusing that they don't match.
![image001](https://user-images.githubusercontent.com/53964/48898703-5ae65a00-ee45-11e8-8535-a170226f0670.png)

**Comment by LBoyle** [comment]
Keep the default version numbering for now, as on left hand side, and in the info panel, just stick SP minor version on the end, e.g. 01.1, 02.3 etc.

**Comment by ng-marcus** [comment]
Fixed.
