### ISSUE TITLE
Atvero Docs not launching

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#479]
Atvero Docs is not launching in the test area

![image](https://user-images.githubusercontent.com/44202559/61442774-28432180-a940-11e9-9967-625659b6fa24.png)

**Comment by ng-lboyle** [comment]
Hi, so I've fixed this problem for B459DOA, just going to test other parts of Atvero to see if there are any knock-on effects. 

This will be a problem for all the older project sites in the test area, I'll try and re-provision them all today to get them up to date.
