### ISSUE TITLE
Adding documents to an issue sheet

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#5]
/sites/A199BRCR/_api/web/lists/getByTitle('DLM_Revisions')/items?$select=ATVMultiRendition/Id,ATVMultiRendition/Created,ATVMultiRendition/ATVServerRelativeUrl,ATVMultiAssocFile/Id,ATVMultiAssocFile/Created,ATVMultiAssocFile/ATVServerRelativeUrl,Title,Modified,GUID,ATVDocumentNumber,Id,ATVRevision,ATVIsIssued,Created,ATVDocumentTitle,ATVContact/Id,ATVContact/Email,ATVStatusLookup/ATVBSStatus,ATVStatusLookup/Id,ATVStatusLookup/Title&$expand=ATVStatusLookup,ATVMultiRendition,ATVMultiAssocFile,ATVContact&$orderby=ID%20desc&$filter=Title%20eq%20%27A199BRCR-CTA-01-ZZ-DR-A-20300%27:1 Failed to load resource: the server responded with a status of 400 ()
/sites/appcatalog/ClientSideAssets/61a94032-8826-4c79-810d-39549dd88b95/ng-component-web-part_3ab81ff5debc0ea3698a4e37091591fa.js:154 Error: Error making HttpClient request in queryable: [400]  ::> {"responseBody":{"odata.error":{"code":"-1, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The field or property 'ATVStatusLookup' does not exist."}}},"responseHeaders":{}}
    at /sites/appcatalog/ClientSideAssets/61a94032-8826-4c79-810d-39549dd88b95/ng-component-web-part_3ab81ff5debc0ea3698a4e37091591fa.js:154
/sites/A199BRCR/_api/web/lists/getByTitle('DLM_Revisions')/items?$select=ATVMultiRendition/Id,ATVMultiRendition/Created,ATVMultiRendition/ATVServerRelativeUrl,ATVMultiAssocFile/Id,ATVMultiAssocFile/Created,ATVMultiAssocFile/ATVServerRelativeUrl,Title,Modified,GUID,ATVDocumentNumber,Id,ATVRevision,ATVIsIssued,Created,ATVDocumentTitle,ATVContact/Id,ATVContact/Email,ATVStatusLookup/ATVBSStatus,ATVStatusLookup/Id,ATVStatusLookup/Title&$expand=ATVStatusLookup,ATVMultiRendition,ATVMultiAssocFile,ATVContact&$orderby=ID%20desc&$filter=Title%20eq%20%27A199BRCR-CTA-01-ZZ-DR-A-20300%27:1 Failed to load resource: the server responded with a status of 400 ()
/sites/appcatalog/ClientSideAssets/61a94032-8826-4c79-810d-39549dd88b95/ng-component-web-part_3ab81ff5debc0ea3698a4e37091591fa.js:154 Error: Error making HttpClient request in queryable: [400]  ::> {"responseBody":{"odata.error":{"code":"-1, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The field or property 'ATVStatusLookup' does not exist."}}},"responseHeaders":{}}
    at /sites/appcatalog/ClientSideAssets/61a94032-8826-4c79-810d-39549dd88b95/ng-component-web-part_3ab81ff5debc0ea3698a4e37091591fa.js:154

**Comment by allanchaplin** [comment]
Hi Stephen,

This bug is fixed in the latest live version.

Allan
