### ISSUE TITLE
DLMS - Drag a file onto the uploader and upload it.  Drag the same file again you get two sets of status

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#51]
![image001](https://user-images.githubusercontent.com/53964/48902412-69863e80-ee50-11e8-8f1d-6eac7347c8fd.png)

**Comment by LBoyle** [comment]
Interesting,
Now if you do this, when you drag on the same file again, the controls disappear, you get a red warning and only option is to press OK, closing and re-opening the side panel. 
This is the case after implementing the new drag and drop uploader.
