### ISSUE TITLE
London Studio Hub Page

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#52]
https://chapmantaylorspace.sharepoint.com/sites/LondonStudio?web=1

Marcus - Can this be bought under the 'UK Studios' HUB page or should I create a new page and delete this one. 

Thanks

**Comment by ng-marcus** [comment]
Hi Stephen,  Sorry for the delay, I'll be on this first thing, and making the Bracknell site page.

**Comment by ng-marcus** [comment]
Unfortunately the conversion to a hubsite is a one way process.   I guess you'd like to keep it as LondonStudio?  If so let me know and I can delete the site, free up the name and recreate it.

**Comment by StephenHiggon01** [comment]
Thanks Marcus – can you please delete to free up the name and I’ll recreate.

Thanks!

Stephen Higgon
Document Manager
shiggon@chapmantaylor.com
