### ISSUE TITLE
Quick part Company Name isn't filled for Word

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#56]
If you create a fee letter, and import the contact from global, the company name isn't set.

If you then use the contact again, all is good.

**Comment by ng-marcus** [comment]
![image](https://user-images.githubusercontent.com/20163757/48939418-0d80f000-ef0c-11e8-8507-0e39de7fc6d4.png)

**Comment by allanchaplin** [comment]
Well that was epic, when you copy a contact the CompanyName field of contact was not getting copied across to the local contact when it was added to the local contact list.
