### ISSUE TITLE
Associated File not showing

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#58]
B459DOA-CTA-02-XX-DR-A-21008 Added an associated file. Upload successful. Still showing as none after 5 mins. 

![image](https://user-images.githubusercontent.com/44202559/48942034-b3852800-ef15-11e8-8812-31a5714585a9.png)

[B459DOA-CTA-02-XX-DR-A-21008 Comment Received.pdf](https://github.com/nittygritty-uk/Atvero-Issues/files/2610610/B459DOA-CTA-02-XX-DR-A-21008.Comment.Received.pdf)

**Comment by allanchaplin** [comment]
Hi Stephen,

Looks like its an issue adding associated files on issued revisions, we're just working on a fix.

Thanks,

Allan

**Comment by allanchaplin** [comment]
Fixed, just making a new release.
