### ISSUE TITLE
Site Photo 

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#59]
https://chapmantaylorspace.sharepoint.com/sites/B459DOA/Site%20Photos/Forms/Thumbnails.aspx

I have added a Picture Library app to the projects but the Text Font changes across SharePoint site. Not sure if this a setting issue due to Atvero plug in? Can you rule it out? Might be a sharepoint quirk!

**Comment by ng-marcus** [comment]
Looks like an issue with the plugin which is now resolved.
