### ISSUE TITLE
Failure to load revisions warning box

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#6]
Failed to load resource: the server responded with a status of 400 ()
ng-component-web-part_3ab81ff5debc0ea3698a4e37091591fa.js:154 Error: Error making HttpClient request in queryable: [400]  ::> {"responseBody":{"odata.error":{"code":"-1, Microsoft.SharePoint.SPException","message":{"lang":"en-US","value":"The field or property 'ATVStatusLookup' does not exist."}}},"responseHeaders":{}}

**Comment by allanchaplin** [comment]
Hi Stephen, this is working on the latest version of the site.

Allan
