### ISSUE TITLE
Display Name at Up Revision

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#60]
Up revised two drawings, system correctly identifies that they are new revs. However the display name changes to drawing number, and does not retain the Drawing title entered from previous revision.

![image](https://user-images.githubusercontent.com/44202559/48943581-94899480-ef1b-11e8-83a4-e1f187a360ee.png)

**Comment by ng-marcus** [comment]
Louis, I think this was fixed today?

**Comment by allanchaplin** [comment]
This is fixed in release 1.0.5.0
