### ISSUE TITLE
Rollback Revision Fail

### ISSUE THREAD

**Issue by StephenHiggon01** [nittygritty-uk/Atvero-Issues#61]
Uploaded three drawings, Rolled back the revision as the revision was incorrect on all three. The roll back has not worked. 

B459DOA-CTA-02-XX-DR-A-21009 - Not showing rev
B459DOA-CTA-02-XX-DR-A-21008 - Showing rev 01 and rev 00
B459DOA-CTA-02-XX-DR-A-21011 - Showing correct rev

I have tried to up revise the revisions again but the system will not allow the revisions to be edited.  

![image](https://user-images.githubusercontent.com/44202559/48944144-791f8900-ef1d-11e8-9404-abe410558371.png)

**Comment by LBoyle** [comment]
I think this is fixed with PR #148
