### ISSUE TITLE
Some Filters no longer work in DLMHome.re

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#73]
Seems pretty well all filters no longer work after pull request #107 (or previous).
The only one that does seem to work is Scale.

**Comment by jim80** [comment]
PCF filter does work

**Comment by LBoyle** [comment]
Most of these are my fault, I've removed all of the fields related to filename from the Placeholder type, and instead storing them in a Js dictionary. I'll make another issue for this.
