### ISSUE TITLE
Naming is problematic for updating a new placeholder

### ISSUE THREAD

**Issue by LBoyle** [nittygritty-uk/Atvero-Issues#78]
So I encountered this bug,
when category is in the template, but not stuck to number, eg [category:2chars]-[number:4chars] with a hyphen,
I still send off the category to the naming lambda, it then generates a number 6 chars long, and rejects me, returns an error. 

Instead of just checking for presence of the category, check also if it's followed by a hyphen, if yes, don't sent it, if no, send it to the naming lambda.

**Comment by allanchaplin** [comment]
Removed the number length check, awaiting PR approval.

**Comment by LBoyle** [comment]
Working. 
There's still the problem of checking whether a number has been used from the front end, I was able to get two placeholders with the same number by not asking for a number, just auto incrementing. 

Not a blocker, I'll make another ticket.
