### ISSUE TITLE
No specific City field, should there be one?

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#8]
Company addresses don't break out the city.  If we did, it could help auto-name addresses?

**Comment by LBoyle** [comment]
Blocked right now, need a new field added to CompanyAddress on the hubsite, but don't want to interfere with the demo.

**Comment by LBoyle** [comment]
PR is out for this, Atvero #72

**Comment by LBoyle** [comment]
Done
