### ISSUE TITLE
Project Factsheet - Overflow is 'single line' text is too long

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#85]
![screenshot 2018-12-12 at 11 58 56](https://user-images.githubusercontent.com/53964/49868459-6d7cff00-fe05-11e8-80d9-5534e4f772b3.png)

**Comment by LBoyle** [comment]
This was because of a combination of bad JSX, and the Fabric title className, Fabric was removing margins and overflow or soemthing. 

I copied the font styles from the ms-font-l and applied them separately in our CSS.

**Comment by LBoyle** [comment]
Fixed in PR 249
