### ISSUE TITLE
Edit contact, dropdowns render before your eyes

### ISSUE THREAD

**Issue by ng-marcus** [nittygritty-uk/Atvero-Issues#9]
Because of the way the selectors work, the drop downs are blank, then have a value as the page loads.  Address is worst as it waits on the company to load.

![image](https://user-images.githubusercontent.com/20163757/48703034-77d32100-ebea-11e8-9568-0642c7878088.png)

**Comment by LBoyle** [comment]
These dropdowns are now disabled until the data they depend on is fully loaded.
