### ISSUE TITLE
Dotx support in templates

### ISSUE THREAD

**Issue by allanchaplin** [nittygritty-uk/Atvero-Issues#99]

**Comment by ng-marcus** [comment]
We assume a file it a .docx and we need to handle any extension.

Also need to check this works for Excel files, and that we can use quickparts with dotx files.

**Comment by ng-marcus** [comment]
Also PPX files for PowerPoint

**Comment by LBoyle** [comment]
I don't really know how quickparts works, how to test it.
Don't know how office templates work.

I've enabled uploads of the template types, dotx, xltx and potx, but word online can't open a dotx, Libre office can open a dotx, but it's no different to a docx.

**Comment by ng-marcus** [comment]
More important is handling doc, xls, xlsx, pptx  rather than .docx files.   I'm pretty sure there's a .docx hardcode in there.

No other app than Word handles quickparts, so the task is actually, can you use an Excel file as a template in the template library / document type?

________________________________

**Comment by ng-marcus** [comment]
Actually, a quick search of the code suggests we don't have a .docx hardcode.

________________________________

**Comment by LBoyle** [comment]
lb-bugfix-99 has the template types allowed in Constants.re, so you can upload them. 
And I'm not really equipped to test excel stuff.

**Comment by LBoyle** [comment]
I don't want to merge this because the template versions of the MS types don't work. 
Word online can't open them.

**Comment by LBoyle** [comment]
I had the wrong end of the stick.

So there was a hardcode in the nativeOpenUrl function to ms-word, meaning when an xlsx gets into the system, the Edit button would try to open it in word. 
Hardcoded a lookup from the file extension to the respective app.
